service: movie-api

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221
  stage: dev 
  region: ap-northeast-2 # 
  environment:
    DB_HOST: ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_HOST} 
    DB_USER: ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_USER} 
    DB_PASSWARD:  ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_PASSWORD} 
    DB_NAME:  ${self:custom.DB_CONFIG.${self:custom.STAGE}.DB_NAME} 
    COLLECTION_NAME:  ${self:custom.DB_CONFIG.${self:custom.STAGE}.COLLECTION_NAME} 

functions:
  get_daily:
    handler: handler.get_daily_movies
    timeout: 30
    memorySize: 256
    events:
      - http:
          method: get
          path: dailyMovies
          request:
            parameters:
              querystrings:
                dt: false
          cors: 
            origin: "*"

  get_weekly:
    handler: handler.get_weekly_movies
    timeout: 30
    memorySize: 256
    events:
      - http:
          method: get
          path: weeklyMovies
          request:
            parameters:
              querystrings:
                dt: false
          cors: 
            origin: "*"


custom:
  STAGE: ${self:provider.stage} 
  DB_CONFIG: ${file(./config/config.js):DB_CONFIG} 
  pythonRequirements:
    useStaticCache: false 
    useDownloadCache: false

    dockerizePip: true
    zip: true 
    slim: true
    # layer: true
    strip: false

plugins: 
  - serverless-python-requirements # 파이썬 외부 라이브러리 용